In [8]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_excel("Churn_Unclean_Project.xlsx")

In [10]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [11]:
df.shape

(542, 18)

In [12]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [13]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(7)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.shape

(535, 18)

In [18]:
df.replace(['N/A','NULL','',' '],np.nan,inplace=True)

In [19]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [20]:
df=df.apply(lambda x: x.str.strip() if x.dtype=="object" else x)

In [21]:
df.head(50)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
5,C1005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
9,C1009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025
10,C1010,Anjali Mehta,Male,60.0,Delhi,Delhi,12.0,Standard,934.28,11411.36,Two Year,Credit Card,DSL,No,Yes,No,YES,03-10-2025
11,C1011,Amit Sharma,Male,NaN,UP,Lucknow,69.0,Premium,1623.70,112278.30,Month-to-Month,Credit Card,Fiber,Yes,Yes,Yes,No,32/13/2025
12,C1012,Priya Gupta,Female,35.0,Maharashtra,Mumbai,18.0,Basic,1722.85,NaN,One Year,Cash,DSL,Yes,No,NaN,Yes,27-09-2025
13,C1013,Neha Verma,Male,3.0,Gujarat,Surat,57.0,Premium,2143.68,122650.76,One Year,Debit Card,Cable,No,No,No,No,09-04-2025
14,C1014,Rahul Singh,Male,41.0,Karnataka,Mysuru,16.0,Premium,2226.93,35184.88,Two Year,Net Banking,Cable,Yes,No,No,No,05-10-2025
15,C1015,Pooja Singh,Male,50.0,Delhi,Noida,16.0,Basic,576.03,9489.48,One Year,Cash,5G,No,No,No,No,01-01-2026
16,C1016,Priya Gupta,Female,120.0,Karnataka,Mysuru,19.0,Standard,1295.83,24158.77,One Year,Net Banking,5G,No,No,Yes,Yes,12-01-2026
17,C1017,Abhishek Jaiswal,Female,NaN,Gujarat,Ahmedabad,48.0,Basic,1975.23,-94534.04,Month-to-Month,Credit Card,Fiber,NaN,No,No,No,13-08-2025
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,04-06-2025
19,C1019,Anjali Mehta,Male,24.0,UP,Lucknow,22.0,Standard,1151.22,25000.84,One Year,Cash,Cable,No,No,Yes,No,05-07-2025
20,C1020,Pooja Singh,Female,22.0,UP,Lucknow,19.0,Premium,1983.04,38142.76,Month-to-Month,Net Banking,5G,NaN,No,Yes,No,27-03-2025
21,C1021,Rohit Kumar,Female,33.0,Maharashtra,Mumbai,38.0,Premium,1294.60,49635.80,One Year,UPI,DSL,Yes,No,Yes,No,26-03-2026
22,C1022,Pooja Singh,Male,4.0,Gujarat,Ahmedabad,70.0,Basic,1260.16,88678.20,One Year,Net Banking,DSL,No,No,No,Yes,27-06-2026
23,C1023,Sneha Jain,Male,48.0,Delhi,Noida,62.0,Basic,430.43,27043.66,Two Year,Credit Card,Cable,No,No,No,No,05-10-2025
24,C1024,Rahul Singh,Female,69.0,Delhi,Noida,60.0,Standard,536.70,32345.00,Two Year,Net Banking,Fiber,No,Yes,No,No,22-01-2026
25,C1025,Anjali Mehta,Male,70.0,NaN,Delhi,42.0,NaN,1516.78,64151.76,Month-to-Month,UPI,Cable,Yes,Yes,Yes,No,06-03-2026
26,C1026,Priya Gupta,Female,60.0,Delhi,Delhi,46.0,Basic,2261.95,103560.70,Month-to-Month,Credit Card,Fiber,Yes,Yes,No,No,29-04-2026
27,C1027,Rahul Singh,Male,5.0,UP,Kanpur,58.0,Premium,1441.72,84097.76,Month-to-Month,Credit Card,5G,Yes,No,No,No,12-06-2026
28,C1028,Pooja Singh,Male,18.0,Delhi,Noida,34.0,Standard,2345.77,80107.18,Month-to-Month,Credit Card,Cable,Yes,No,Yes,No,17-08-2025
29,C1029,Mohit Arora,Female,25.0,Gujarat,Surat,63.0,Premium,2453.94,154710.22,Month-to-Month,Debit Card,Fiber,Yes,No,Yes,No,02-08-2025
30,C1030,Pooja Singh,Female,40.0,Delhi,Noida,35.0,Premium,1875.48,65975.80,Month-to-Month,Credit Card,Fiber,No,No,Yes,Yes,16-01-2025
31,C1031,Abhishek Jaiswal,Male,37.0,UP,NaN,23.0,Premium,1555.38,35431.74,One Year,Debit Card,Fiber,Yes,No,No,Yes,26-06-2026
32,C1032,Vikas Yadav,Male,19.0,UP,Lucknow,71.0,Standard,575.49,40687.79,One Year,Credit Card,Fiber,Yes,No,Yes,No,25-04-2026
33,C1033,Vikas Yadav,Male,37.0,UP,Kanpur,28.0,Premium,1848.11,52054.08,Month-to-Month,Cash,Fiber,No,No,Yes,No,04-01-2026
34,C1034,Amit Sharma,Male,29.0,Karnataka,Bengaluru,38.0,Standard,1399.37,52996.06,Month-to-Month,Cash,DSL,Yes,No,Yes,No,18-04-2026
35,C1035,Rahul Singh,Female,38.0,Karnataka,Bengaluru,57.0,Basic,1576.89,89544.73,Month-to-Month,Cash,Fiber,Yes,No,No,No,07-12-2025
36,C1036,Rohit Kumar,Male,48.0,UP,Kanpur,70.0,Premium,1285.52,-89554.40,Month-to-Month,UPI,Cable,No,No,No,No,04-04-2025
37,C1037,Rahul Singh,Male,18.0,Gujarat,Ahmedabad,72.0,Standard,546.66,38971.52,Month-to-Month,Debit Card,Fiber,Yes,No,No,No,21-09-2025
38,C1038,Rohit Kumar,Male,21.0,Delhi,Delhi,1.0,Standard,1028.83,684.83,Two Year,UPI,Cable,NaN,No,No,No,29-04-2026
39,C1039,Pooja Singh,Female,68.0,Karnataka,Mysuru,16.0,Standard,1242.87,19725.92,One Year,Net Banking,Fiber,No,Yes,No,Yes,12-06-2026
40,C1040,Pooja Singh,Female,28.0,UP,Lucknow,29.0,Standard,1076.14,30815.06,Two Year,Debit Card,Fiber,Yes,No,No,No,17-07-2025
41,C1041,Vikas Yadav,Male,36.0,Delhi,Delhi,71.0,Premium,1432.25,101365.75,One Year,Debit Card,Fiber,No,No,Yes,No,16-10-2025
42,C1042,Vikas Yadav,Female,23.0,Delhi,Noida,50.0,Basic,1652.97,82739.50,Month-to-Month,Credit Card,DSL,Yes,No,Yes,yes,29-01-2026
43,C1043,Vikas Yadav,Male,41.0,UP,Kanpur,5.0,Basic,1807.65,8698.25,Month-to-Month,Credit Card,DSL,No,No,No,No,01-06-2026
44,C1044,Neha Verma,Female,44.0,UP,Kanpur,59.0,Basic,1165.44,69124.96,Two Year,Cash,DSL,No,No,No,No,06-10-2025
45,C1045,Rahul Singh,Female,58.0,Gujarat,Ahmedabad,72.0,Basic,1255.14,90083.08,One Year,Credit Card,DSL,Yes,No,No,No,16-11-2025
46,C1046,Sneha Jain,Female,140.0,Maharashtra,Pune,62.0,Basic,NaN,34002.48,Two Year,Cash,DSL,Yes,No,Yes,No,01-09-2025
47,C1047,Amit Sharma,Male,25.0,UP,Lucknow,68.0,Premium,2331.64,158350.52,Month-to-Month,Cash,DSL,Yes,No,Yes,No,21-01-2025
48,C1048,Neha Verma,Male,19.0,Delhi,Noida,59.0,Standard,1596.90,93810.10,Two Year,Cash,5G,No,No,Yes,Yes,25-01-2026
49,C1049,Priya Gupta,Male,47.0,Delhi,Noida,14.0,Standard,2176.11,30072.54,Month-to-Month,Debit Card,Cable,No,No,Yes,Yes,17-05-2026

In [22]:
df['Customer_Name']=df['Customer_Name'].str.title()
df['Gender']=df['Gender'].str.title()
df['State']=df['State'].str.title()
df['City']=df['City'].str.title()
df['Subscription_Type']=df['Subscription_Type'].str.title()
df['Contract_Type']=df['Contract_Type'].str.title()
df['Payment_Method']=df['Payment_Method'].str.title()
df['Internet_Service']=df['Internet_Service'].str.title()
df['Tech_Support']=df['Tech_Support'].str.title()
df['Senior_Citizen']=df['Senior_Citizen'].str.title()
df['Dependents']=df['Dependents'].str.title()
df['Churn']=df['Churn'].str.title()

In [23]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,Upi,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,Dsl,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,Upi,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [24]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [25]:
df['Churn'].value_counts()

Churn
No     405
Yes    127
Name: count, dtype: int64

In [26]:
cols=('Age','Tenure_Months','Monthly_Charges','Total_Charges')
for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    object
 1   Customer_Name          527 non-null    object
 2   Gender                 530 non-null    object
 3   Age                    529 non-null    float64
 4   State                  525 non-null    object
 5   City                   530 non-null    object
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    object
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    object
 11  Payment_Method         520 non-null    object
 12  Internet_Service       529 non-null    object
 13  Tech_Support           524 non-null    object
 14  Senior_Citizen         528 non-null    object
 15  Dependents             533 non-null    object
 16  Churn                  532 non-null    object
 17  Last_Interaction_Date  533 non-null    object
dtypes: float64(4), object(14)
memory usage: 79.4+ KB

In [28]:
df['Last_Interaction_Date']=pd.to_datetime(df['Last_Interaction_Date'],errors="coerce")

In [29]:
df=df[(df['Age']>=18)&(df['Age']<=100)]

In [30]:
df=df[df['Monthly_Charges']>=0]
df=df[df['Total_Charges']>=0]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          487 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         477 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           483 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  178 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(13)
memory usage: 73.0+ KB

In [32]:
df['Tech_Support']=df['Tech_Support'].fillna("No")
df['Payment_Method']=df['Payment_Method'].fillna("Unknown")
df['Monthly_Charges']=df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean())
df['Tenure_Months']=df['Tenure_Months'].fillna(df['Tenure_Months'].mean())
df['Age']=df['Age'].fillna(df['Age'].mean())

In [33]:
df['Customer_Value']=df['Monthly_Charges']*df['Tenure_Months']

In [34]:
df['Monthly_Revenue']=df['Monthly_Charges']

In [35]:
bins=[0,12,24,48,72]
label=labels=["0-12 month","13-24 month","25-48 month","49-72 month"]
df['Tenure_Group']=pd.cut(df['Tenure_Months'],bins=bins,labels=label)

In [36]:
df["Senior_Flag"]=np.where(df['Age']>=60,'Senior','Adult')

In [37]:
df["Churn_Flag"]=df["Churn"].map({"Yes":1,"No":0})

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    object
 1   Customer_Name          487 non-null    object
 2   Gender                 488 non-null    object
 3   Age                    492 non-null    float64
 4   State                  485 non-null    object
 5   City                   487 non-null    object
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    object
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    object
 11  Payment_Method         492 non-null    object
 12  Internet_Service       486 non-null    object
 13  Tech_Support           492 non-null    object
 14  Senior_Citizen         486 non-null    object
 15  Dependents             491 non-null    object
 16  Churn                  490 non-null    object
 17  Last_Interaction_Date  178 non-null    datetime64[ns]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    object
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(7), object(14)
memory usage: 89.1+ KB

In [39]:
df['Last_Interaction_Date']=df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

In [40]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df.to_csv("Clean_Churn_Data.csv",index=False)

In [43]:
pip install psycopg2.binary sqlalchemy

Requirement already satisfied: psycopg2.binary in c:\users\sayandeep\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\sayandeep\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sayandeep\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
from sqlalchemy import create_engine
username = "postgres"
password= "sayandeep12345"
host= "localhost"
port="5432"
database= "Customer_Churn_Database"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name="customer_churn"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"data successfully loaded into table '{table_name}' in database '{database}'.")

data successfully loaded into table 'customer_churn' in database 'Customer_Churn_Database'.